module.exports = {
    KEY: 'SET YOUR PASSWORD KEY',
    VRCHAT_COOKIE: 'ENTER YOUR VRCHAT COOKIE',
    DB_PASSWORD: 'ENTER YOUR ARANGODB PASSWORD',
    CLOUDFLARE_API_KEY: '',
    CLOUDFLARE_ACCOUNT_ID: '',
    CLOUDFLARE_ACCOUT_HASH: '',
};